export interface PageDetail {
  path: string;
  traffic: number;
  share: string;
  bounceRate: number;
  avgDuration: string;
  avgDurationSec: number;
  pagesPerVisit: number;
  trend: "up" | "down" | "stable";
  category: string;
}

export interface SiteData {
  id: string;
  name: string;
  domain: string;
  color: string;
  visits: number;
  visitsDisplay: string;
  globalRank: number;
  countryRank: number;
  authorityScore: number;
  bounceRate: number;
  pagesPerVisit: number;
  avgDuration: string;
  organicTraffic: string;
  organicChange: number;
  paidTraffic: string;
  paidChange: number;
  refDomains: number;
  refDomainsChange: number;
  totalBacklinks: number;
  backlinksChange: number;
  aiTraffic: number;
  channels: Record<string, number>;
  keywords: { rank: number; keyword: string; position: number; volume: number; trafficShare: string }[];
  monthlyVisits: { month: string; value: number }[];
  topPages: { path: string; traffic: number; share: string }[];
  pageDetails: PageDetail[];
}

export const SITES: SiteData[] = [
  {
    id: "info",
    name: "infoyatirim.com",
    domain: "infoyatirim.com",
    color: "#f59e0b",
    visits: 471350,
    visitsDisplay: "471.4K",
    globalRank: 86118,
    countryRank: 1981,
    authorityScore: 45,
    bounceRate: 66.65,
    pagesPerVisit: 6.98,
    avgDuration: "8dk 13sn",
    organicTraffic: "210.9K",
    organicChange: -9,
    paidTraffic: "2.13K",
    paidChange: -44,
    refDomains: 1840,
    refDomainsChange: 7,
    totalBacklinks: 27290,
    backlinksChange: -23,
    aiTraffic: 223,
    channels: { direct: 70.23, organic: 24.58, referral: 2, social: 1, paid: 1, mail: 1 },
    keywords: [
      { rank: 1, keyword: "halka arz takvimi", position: 2, volume: 1000, trafficShare: "%12.43" },
      { rank: 2, keyword: "canlı borsa", position: 10, volume: 368000, trafficShare: "%5.25" },
      { rank: 3, keyword: "sermaye artırımı", position: 2, volume: 1000, trafficShare: "%2.87" },
      { rank: 4, keyword: "sasa hisse", position: 3, volume: 4090000, trafficShare: "%1.36" },
      { rank: 5, keyword: "ist: kchol", position: 8, volume: 60500, trafficShare: "%0.86" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 180 }, { month: "Şub", value: 210 }, { month: "Mar", value: 260 },
      { month: "Nis", value: 310 }, { month: "May", value: 380 }, { month: "Haz", value: 471 },
    ],
    topPages: [
      { path: "/halka-arz-takvimi", traffic: 58568, share: "%12.43" },
      { path: "/canli-borsa", traffic: 24734, share: "%5.25" },
      { path: "/sermaye-artirimi", traffic: 13524, share: "%2.87" },
    ],
    pageDetails: [
      { path: "/halka-arz-takvimi", traffic: 58568, share: "%12.43", bounceRate: 72, avgDuration: "1dk 20sn", avgDurationSec: 80, pagesPerVisit: 1.2, trend: "stable", category: "araç" },
      { path: "/canli-borsa", traffic: 24734, share: "%5.25", bounceRate: 65, avgDuration: "3dk 45sn", avgDurationSec: 225, pagesPerVisit: 2.8, trend: "up", category: "araç" },
      { path: "/sermaye-artirimi", traffic: 13524, share: "%2.87", bounceRate: 35, avgDuration: "4dk 12sn", avgDurationSec: 252, pagesPerVisit: 4.5, trend: "stable", category: "içerik" },
      { path: "/endeks/bist-100", traffic: 8500, share: "%1.80", bounceRate: 48, avgDuration: "5dk 10sn", avgDurationSec: 310, pagesPerVisit: 3.2, trend: "up", category: "veri" },
      { path: "/hisse/sasa", traffic: 6400, share: "%1.36", bounceRate: 42, avgDuration: "6dk 30sn", avgDurationSec: 390, pagesPerVisit: 3.8, trend: "stable", category: "hisse" },
      { path: "/altin-fiyatlari", traffic: 5200, share: "%1.10", bounceRate: 58, avgDuration: "2dk 30sn", avgDurationSec: 150, pagesPerVisit: 1.8, trend: "up", category: "veri" },
      { path: "/hisse/aselsan", traffic: 4100, share: "%0.87", bounceRate: 38, avgDuration: "7dk 15sn", avgDurationSec: 435, pagesPerVisit: 4.2, trend: "stable", category: "hisse" },
      { path: "/blog/2026-yatirim-stratejisi", traffic: 2800, share: "%0.59", bounceRate: 28, avgDuration: "8dk 45sn", avgDurationSec: 525, pagesPerVisit: 5.5, trend: "stable", category: "blog" },
    ],
  },
  {
    id: "gcm",
    name: "gcmyatirim.com.tr",
    domain: "gcmyatirim.com.tr",
    color: "#3b82f6",
    visits: 2010000,
    visitsDisplay: "2.01M",
    globalRank: 25044,
    countryRank: 504,
    authorityScore: 54,
    bounceRate: 91.84,
    pagesPerVisit: 1.30,
    avgDuration: "10dk 47sn",
    organicTraffic: "2.41M",
    organicChange: -4,
    paidTraffic: "2.72M",
    paidChange: -27,
    refDomains: 2500,
    refDomainsChange: 3,
    totalBacklinks: 974770,
    backlinksChange: -9,
    aiTraffic: 448,
    channels: { direct: 63.7, organic: 17.56, referral: 8, social: 4, paid: 5, mail: 1.74 },
    keywords: [
      { rank: 1, keyword: "tam altın fiyatı", position: 1, volume: 450000, trafficShare: "%8.82" },
      { rank: 2, keyword: "ceyrek altin fiyati", position: 12, volume: 246000, trafficShare: "%4.82" },
      { rank: 3, keyword: "çeyrek altın fiyatı", position: 3, volume: 2240000, trafficShare: "%3.73" },
      { rank: 4, keyword: "çeyrek altın ne kadar", position: 5, volume: 1830000, trafficShare: "%2.28" },
      { rank: 5, keyword: "sasa hisse", position: 9, volume: 4090000, trafficShare: "%2.21" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 1850 }, { month: "Şub", value: 1920 }, { month: "Mar", value: 1880 },
      { month: "Nis", value: 1950 }, { month: "May", value: 2010 }, { month: "Haz", value: 2010 },
    ],
    topPages: [
      { path: "/altin/tam-altin-fiyati", traffic: 177282, share: "%8.82" },
      { path: "/altin/ceyrek-altin", traffic: 96882, share: "%4.82" },
      { path: "/altin", traffic: 74973, share: "%3.73" },
    ],
    pageDetails: [
      { path: "/altin/tam-altin-fiyati", traffic: 177282, share: "%8.82", bounceRate: 94, avgDuration: "45sn", avgDurationSec: 45, pagesPerVisit: 1.1, trend: "stable", category: "veri" },
      { path: "/altin/ceyrek-altin", traffic: 96882, share: "%4.82", bounceRate: 93, avgDuration: "40sn", avgDurationSec: 40, pagesPerVisit: 1.1, trend: "stable", category: "veri" },
      { path: "/altin", traffic: 74973, share: "%3.73", bounceRate: 89, avgDuration: "1dk 10sn", avgDurationSec: 70, pagesPerVisit: 1.3, trend: "up", category: "veri" },
      { path: "/yatirim", traffic: 30000, share: "%1.49", bounceRate: 75, avgDuration: "2dk 30sn", avgDurationSec: 150, pagesPerVisit: 2.0, trend: "down", category: "içerik" },
      { path: "/doviz", traffic: 25000, share: "%1.24", bounceRate: 88, avgDuration: "1dk 00sn", avgDurationSec: 60, pagesPerVisit: 1.2, trend: "stable", category: "veri" },
    ],
  },
  {
    id: "isy",
    name: "isyatirim.com.tr",
    domain: "isyatirim.com.tr",
    color: "#a855f7",
    visits: 346460,
    visitsDisplay: "346.5K",
    globalRank: 110338,
    countryRank: 2748,
    authorityScore: 59,
    bounceRate: 63.49,
    pagesPerVisit: 2.25,
    avgDuration: "6dk 22sn",
    organicTraffic: "2.80M",
    organicChange: -1,
    paidTraffic: "0",
    paidChange: 0,
    refDomains: 3140,
    refDomainsChange: -13,
    totalBacklinks: 69540,
    backlinksChange: -10,
    aiTraffic: 996,
    channels: { direct: 52.87, organic: 36.4, referral: 5, social: 3, paid: 0, mail: 2.73 },
    keywords: [
      { rank: 1, keyword: "sasa hisse", position: 3, volume: 4090000, trafficShare: "%7.38" },
      { rank: 2, keyword: "bist 100", position: 7, volume: 1830000, trafficShare: "%1.98" },
      { rank: 3, keyword: "aselsan hisse", position: 3, volume: 1220000, trafficShare: "%1.76" },
      { rank: 4, keyword: "tüpraş hisse", position: 3, volume: 673000, trafficShare: "%1.21" },
      { rank: 5, keyword: "hisse", position: 11, volume: 35000, trafficShare: "%2.29" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 320 }, { month: "Şub", value: 335 }, { month: "Mar", value: 340 },
      { month: "Nis", value: 342 }, { month: "May", value: 345 }, { month: "Haz", value: 346 },
    ],
    topPages: [
      { path: "/hisse/sasa", traffic: 25568, share: "%7.38" },
      { path: "/endeks/bist-100", traffic: 6858, share: "%1.98" },
      { path: "/hisse/aselsan", traffic: 6098, share: "%1.76" },
    ],
    pageDetails: [
      { path: "/hisse/sasa", traffic: 25568, share: "%7.38", bounceRate: 45, avgDuration: "5dk 30sn", avgDurationSec: 330, pagesPerVisit: 3.5, trend: "stable", category: "hisse" },
      { path: "/endeks/bist-100", traffic: 6858, share: "%1.98", bounceRate: 50, avgDuration: "4dk 00sn", avgDurationSec: 240, pagesPerVisit: 2.8, trend: "up", category: "veri" },
      { path: "/hisse/aselsan", traffic: 6098, share: "%1.76", bounceRate: 42, avgDuration: "6dk 15sn", avgDurationSec: 375, pagesPerVisit: 3.8, trend: "stable", category: "hisse" },
      { path: "/hisse/tupra", traffic: 4500, share: "%1.30", bounceRate: 44, avgDuration: "5dk 45sn", avgDurationSec: 345, pagesPerVisit: 3.2, trend: "stable", category: "hisse" },
      { path: "/arastirma", traffic: 3200, share: "%0.92", bounceRate: 38, avgDuration: "7dk 20sn", avgDurationSec: 440, pagesPerVisit: 4.5, trend: "up", category: "içerik" },
    ],
  },
  {
    id: "ged",
    name: "gedik.com",
    domain: "gedik.com",
    color: "#22c55e",
    visits: 306850,
    visitsDisplay: "306.9K",
    globalRank: 121621,
    countryRank: 3054,
    authorityScore: 50,
    bounceRate: 53.86,
    pagesPerVisit: 2.70,
    avgDuration: "6dk 50sn",
    organicTraffic: "439.9K",
    organicChange: -2,
    paidTraffic: "4.71K",
    paidChange: 2,
    refDomains: 2260,
    refDomainsChange: 1,
    totalBacklinks: 98030,
    backlinksChange: 0,
    aiTraffic: 61,
    channels: { direct: 69.11, organic: 24.66, referral: 3, social: 2, paid: 1, mail: 0.23 },
    keywords: [
      { rank: 1, keyword: "ons altın", position: 6, volume: 1220000, trafficShare: "%13.97" },
      { rank: 2, keyword: "gedik yatırım", position: 1, volume: 12100, trafficShare: "%2.21" },
      { rank: 3, keyword: "altın ons", position: 7, volume: 165000, trafficShare: "%1.51" },
      { rank: 4, keyword: "faiz", position: 3, volume: 246000, trafficShare: "%1.40" },
      { rank: 5, keyword: "gedik", position: 1, volume: 9900, trafficShare: "%1.81" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 290 }, { month: "Şub", value: 295 }, { month: "Mar", value: 300 },
      { month: "Nis", value: 302 }, { month: "May", value: 305 }, { month: "Haz", value: 307 },
    ],
    topPages: [
      { path: "/yatirim/altin/ons-altin", traffic: 42866, share: "%13.97" },
      { path: "/kurumsal", traffic: 6778, share: "%2.21" },
      { path: "/yatirim/altin", traffic: 4633, share: "%1.51" },
    ],
    pageDetails: [
      { path: "/yatirim/altin/ons-altin", traffic: 42866, share: "%13.97", bounceRate: 55, avgDuration: "3dk 20sn", avgDurationSec: 200, pagesPerVisit: 2.2, trend: "stable", category: "veri" },
      { path: "/kurumsal", traffic: 6778, share: "%2.21", bounceRate: 60, avgDuration: "2dk 45sn", avgDurationSec: 165, pagesPerVisit: 2.5, trend: "stable", category: "kurumsal" },
      { path: "/yatirim/altin", traffic: 4633, share: "%1.51", bounceRate: 52, avgDuration: "3dk 50sn", avgDurationSec: 230, pagesPerVisit: 2.8, trend: "stable", category: "veri" },
      { path: "/yatirim", traffic: 3500, share: "%1.14", bounceRate: 48, avgDuration: "4dk 30sn", avgDurationSec: 270, pagesPerVisit: 3.0, trend: "up", category: "içerik" },
      { path: "/doviz", traffic: 2800, share: "%0.91", bounceRate: 58, avgDuration: "2dk 15sn", avgDurationSec: 135, pagesPerVisit: 1.8, trend: "down", category: "veri" },
    ],
  },
  {
    id: "midas",
    name: "getmidas.com",
    domain: "getmidas.com",
    color: "#ef4444",
    visits: 1800000,
    visitsDisplay: "1.80M",
    globalRank: 35000,
    countryRank: 700,
    authorityScore: 64,
    bounceRate: 75,
    pagesPerVisit: 2.50,
    avgDuration: "5dk 00sn",
    organicTraffic: "1.20M",
    organicChange: 15,
    paidTraffic: "50.0K",
    paidChange: 10,
    refDomains: 735,
    refDomainsChange: 8,
    totalBacklinks: 12000,
    backlinksChange: 5,
    aiTraffic: 500,
    channels: { direct: 65, organic: 28, referral: 3, social: 2, paid: 1, mail: 1 },
    keywords: [
      { rank: 1, keyword: "bist 100", position: 1, volume: 1830000, trafficShare: "%10.93" },
      { rank: 2, keyword: "borsa istanbul", position: 2, volume: 450000, trafficShare: "%5.20" },
      { rank: 3, keyword: "hisse senedi", position: 3, volume: 90000, trafficShare: "%3.50" },
      { rank: 4, keyword: "bist 30", position: 4, volume: 40000, trafficShare: "%2.80" },
      { rank: 5, keyword: "borsa", position: 5, volume: 135000, trafficShare: "%2.10" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 1500 }, { month: "Şub", value: 1550 }, { month: "Mar", value: 1600 },
      { month: "Nis", value: 1700 }, { month: "May", value: 1750 }, { month: "Haz", value: 1800 },
    ],
    topPages: [
      { path: "/bist-100", traffic: 196800, share: "%10.93" },
      { path: "/borsa-istanbul", traffic: 93600, share: "%5.20" },
      { path: "/hisse-senedi", traffic: 63000, share: "%3.50" },
    ],
    pageDetails: [
      { path: "/bist-100", traffic: 196800, share: "%10.93", bounceRate: 70, avgDuration: "2dk 10sn", avgDurationSec: 130, pagesPerVisit: 1.8, trend: "up", category: "veri" },
      { path: "/borsa-istanbul", traffic: 93600, share: "%5.20", bounceRate: 68, avgDuration: "2dk 30sn", avgDurationSec: 150, pagesPerVisit: 2.0, trend: "up", category: "veri" },
      { path: "/hisse-senedi", traffic: 63000, share: "%3.50", bounceRate: 65, avgDuration: "3dk 00sn", avgDurationSec: 180, pagesPerVisit: 2.2, trend: "stable", category: "içerik" },
      { path: "/canli-borsa", traffic: 45000, share: "%2.50", bounceRate: 72, avgDuration: "4dk 30sn", avgDurationSec: 270, pagesPerVisit: 3.5, trend: "up", category: "araç" },
      { path: "/kredi", traffic: 30000, share: "%1.67", bounceRate: 60, avgDuration: "3dk 45sn", avgDurationSec: 225, pagesPerVisit: 2.5, trend: "up", category: "finans" },
    ],
  },
  {
    id: "a1c",
    name: "a1capital.com.tr",
    domain: "a1capital.com.tr",
    color: "#f97316",
    visits: 144960,
    visitsDisplay: "145.0K",
    globalRank: 220175,
    countryRank: 6083,
    authorityScore: 38,
    bounceRate: 77.88,
    pagesPerVisit: 2.46,
    avgDuration: "20dk 36sn",
    organicTraffic: "38.02K",
    organicChange: -18,
    paidTraffic: "8.44K",
    paidChange: -50,
    refDomains: 802,
    refDomainsChange: 3,
    totalBacklinks: 22640,
    backlinksChange: -44,
    aiTraffic: 50,
    channels: { direct: 84, organic: 12, referral: 2, social: 1, paid: 1, mail: 0 },
    keywords: [
      { rank: 1, keyword: "a1 capital", position: 1, volume: 8100, trafficShare: "%5.59" },
      { rank: 2, keyword: "a1 yatırım", position: 2, volume: 3600, trafficShare: "%3.20" },
      { rank: 3, keyword: "canlı borsa", position: 5, volume: 368000, trafficShare: "%2.80" },
      { rank: 4, keyword: "borsa", position: 8, volume: 135000, trafficShare: "%1.90" },
      { rank: 5, keyword: "halka arz", position: 6, volume: 70000, trafficShare: "%1.50" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 130 }, { month: "Şub", value: 140 }, { month: "Mar", value: 145 },
      { month: "Nis", value: 148 }, { month: "May", value: 150 }, { month: "Haz", value: 145 },
    ],
    topPages: [
      { path: "/", traffic: 8100, share: "%5.59" },
      { path: "/borsa", traffic: 4060, share: "%2.80" },
      { path: "/halka-arz", traffic: 2174, share: "%1.50" },
    ],
    pageDetails: [
      { path: "/", traffic: 8100, share: "%5.59", bounceRate: 78, avgDuration: "1dk 30sn", avgDurationSec: 90, pagesPerVisit: 1.5, trend: "down", category: "ana sayfa" },
      { path: "/borsa", traffic: 4060, share: "%2.80", bounceRate: 75, avgDuration: "2dk 00sn", avgDurationSec: 120, pagesPerVisit: 1.8, trend: "stable", category: "veri" },
      { path: "/halka-arz", traffic: 2174, share: "%1.50", bounceRate: 65, avgDuration: "3dk 15sn", avgDurationSec: 195, pagesPerVisit: 2.5, trend: "stable", category: "içerik" },
      { path: "/arastirma", traffic: 1500, share: "%1.03", bounceRate: 55, avgDuration: "4dk 30sn", avgDurationSec: 270, pagesPerVisit: 3.2, trend: "up", category: "içerik" },
      { path: "/kurumsal", traffic: 1200, share: "%0.83", bounceRate: 70, avgDuration: "2dk 15sn", avgDurationSec: 135, pagesPerVisit: 2.0, trend: "stable", category: "kurumsal" },
    ],
  },
  {
    id: "tera",
    name: "terayatirim.com",
    domain: "terayatirim.com",
    color: "#06b6d4",
    visits: 52220,
    visitsDisplay: "52.2K",
    globalRank: 486962,
    countryRank: 15187,
    authorityScore: 36,
    bounceRate: 26.7,
    pagesPerVisit: 4.41,
    avgDuration: "3dk 03sn",
    organicTraffic: "74.03K",
    organicChange: 40,
    paidTraffic: "0",
    paidChange: 0,
    refDomains: 363,
    refDomainsChange: 3,
    totalBacklinks: 4400,
    backlinksChange: 7,
    aiTraffic: 30,
    channels: { direct: 53.46, organic: 40, referral: 3, social: 2, paid: 0, mail: 1.54 },
    keywords: [
      { rank: 1, keyword: "tera yatirim menkul degerler as", position: 1, volume: 33100, trafficShare: "%63.39" },
      { rank: 2, keyword: "canlı borsa", position: 4, volume: 368000, trafficShare: "%8.20" },
      { rank: 3, keyword: "borsa", position: 7, volume: 135000, trafficShare: "%4.10" },
      { rank: 4, keyword: "hisse", position: 6, volume: 35000, trafficShare: "%3.50" },
      { rank: 5, keyword: "bist", position: 9, volume: 60000, trafficShare: "%2.80" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 45 }, { month: "Şub", value: 48 }, { month: "Mar", value: 50 },
      { month: "Nis", value: 50 }, { month: "May", value: 52 }, { month: "Haz", value: 52 },
    ],
    topPages: [
      { path: "/", traffic: 33100, share: "%63.39" },
      { path: "/canli-borsa", traffic: 4282, share: "%8.20" },
      { path: "/hisse", traffic: 1828, share: "%3.50" },
    ],
    pageDetails: [
      { path: "/", traffic: 33100, share: "%63.39", bounceRate: 28, avgDuration: "2dk 45sn", avgDurationSec: 165, pagesPerVisit: 4.0, trend: "up", category: "ana sayfa" },
      { path: "/canli-borsa", traffic: 4282, share: "%8.20", bounceRate: 35, avgDuration: "4dk 15sn", avgDurationSec: 255, pagesPerVisit: 3.5, trend: "up", category: "araç" },
      { path: "/hisse", traffic: 1828, share: "%3.50", bounceRate: 30, avgDuration: "5dk 30sn", avgDurationSec: 330, pagesPerVisit: 4.2, trend: "stable", category: "içerik" },
      { path: "/arastirma", traffic: 1200, share: "%2.30", bounceRate: 25, avgDuration: "7dk 00sn", avgDurationSec: 420, pagesPerVisit: 5.0, trend: "up", category: "içerik" },
      { path: "/iletisim", traffic: 800, share: "%1.53", bounceRate: 50, avgDuration: "1dk 30sn", avgDurationSec: 90, pagesPerVisit: 1.5, trend: "stable", category: "kurumsal" },
    ],
  },
  {
    id: "osm",
    name: "osmanlimenkul.com.tr",
    domain: "osmanlimenkul.com.tr",
    color: "#ec4899",
    visits: 236350,
    visitsDisplay: "236.4K",
    globalRank: 150000,
    countryRank: 4820,
    authorityScore: 40,
    bounceRate: 65,
    pagesPerVisit: 2.50,
    avgDuration: "4dk 00sn",
    organicTraffic: "20.23K",
    organicChange: 10,
    paidTraffic: "101.82K",
    paidChange: 13,
    refDomains: 500,
    refDomainsChange: 5,
    totalBacklinks: 8000,
    backlinksChange: 3,
    aiTraffic: 100,
    channels: { direct: 52.83, organic: 42.21, referral: 2, social: 1, paid: 2, mail: 0 },
    keywords: [
      { rank: 1, keyword: "osmanlı yatırım", position: 1, volume: 6600, trafficShare: "%4.50" },
      { rank: 2, keyword: "borsa", position: 6, volume: 135000, trafficShare: "%3.80" },
      { rank: 3, keyword: "canlı borsa", position: 8, volume: 368000, trafficShare: "%3.20" },
      { rank: 4, keyword: "altın", position: 9, volume: 200000, trafficShare: "%2.50" },
      { rank: 5, keyword: "hisse", position: 7, volume: 35000, trafficShare: "%2.10" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 200 }, { month: "Şub", value: 210 }, { month: "Mar", value: 220 },
      { month: "Nis", value: 230 }, { month: "May", value: 236 }, { month: "Haz", value: 236 },
    ],
    topPages: [
      { path: "/", traffic: 10636, share: "%4.50" },
      { path: "/borsa", traffic: 8981, share: "%3.80" },
      { path: "/altin", traffic: 5909, share: "%2.50" },
    ],
    pageDetails: [
      { path: "/", traffic: 10636, share: "%4.50", bounceRate: 62, avgDuration: "2dk 30sn", avgDurationSec: 150, pagesPerVisit: 2.2, trend: "stable", category: "ana sayfa" },
      { path: "/borsa", traffic: 8981, share: "%3.80", bounceRate: 60, avgDuration: "2dk 45sn", avgDurationSec: 165, pagesPerVisit: 2.5, trend: "stable", category: "veri" },
      { path: "/altin", traffic: 5909, share: "%2.50", bounceRate: 65, avgDuration: "2dk 00sn", avgDurationSec: 120, pagesPerVisit: 1.8, trend: "up", category: "veri" },
      { path: "/hisse", traffic: 3500, share: "%1.48", bounceRate: 55, avgDuration: "3dk 30sn", avgDurationSec: 210, pagesPerVisit: 2.8, trend: "stable", category: "hisse" },
      { path: "/kurumsal", traffic: 2000, share: "%0.85", bounceRate: 58, avgDuration: "2dk 15sn", avgDurationSec: 135, pagesPerVisit: 2.0, trend: "stable", category: "kurumsal" },
    ],
  },
  {
    id: "unlu",
    name: "unlumenkul.com",
    domain: "unlumenkul.com",
    color: "#14b8a6",
    visits: 35000,
    visitsDisplay: "35.0K",
    globalRank: 600000,
    countryRank: 18000,
    authorityScore: 56,
    bounceRate: 70,
    pagesPerVisit: 2.00,
    avgDuration: "3dk 00sn",
    organicTraffic: "21.6K",
    organicChange: 5,
    paidTraffic: "0",
    paidChange: 0,
    refDomains: 212,
    refDomainsChange: 2,
    totalBacklinks: 3000,
    backlinksChange: 3,
    aiTraffic: 20,
    channels: { direct: 55, organic: 38, referral: 3, social: 2, paid: 0, mail: 2 },
    keywords: [
      { rank: 1, keyword: "tüpraş temettü 2024", position: 1, volume: 8100, trafficShare: "%23.14" },
      { rank: 2, keyword: "tüpraş temettü", position: 2, volume: 5400, trafficShare: "%12.50" },
      { rank: 3, keyword: "temettü", position: 4, volume: 30000, trafficShare: "%8.20" },
      { rank: 4, keyword: "borsa", position: 10, volume: 135000, trafficShare: "%4.50" },
      { rank: 5, keyword: "hisse", position: 8, volume: 35000, trafficShare: "%3.80" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 30 }, { month: "Şub", value: 32 }, { month: "Mar", value: 33 },
      { month: "Nis", value: 34 }, { month: "May", value: 35 }, { month: "Haz", value: 35 },
    ],
    topPages: [
      { path: "/temettu", traffic: 8100, share: "%23.14" },
      { path: "/", traffic: 4375, share: "%12.50" },
      { path: "/hisse", traffic: 1330, share: "%3.80" },
    ],
    pageDetails: [
      { path: "/temettu", traffic: 8100, share: "%23.14", bounceRate: 60, avgDuration: "3dk 00sn", avgDurationSec: 180, pagesPerVisit: 2.5, trend: "stable", category: "içerik" },
      { path: "/", traffic: 4375, share: "%12.50", bounceRate: 68, avgDuration: "1dk 45sn", avgDurationSec: 105, pagesPerVisit: 1.8, trend: "stable", category: "ana sayfa" },
      { path: "/hisse", traffic: 1330, share: "%3.80", bounceRate: 55, avgDuration: "4dk 00sn", avgDurationSec: 240, pagesPerVisit: 3.0, trend: "stable", category: "hisse" },
      { path: "/arastirma", traffic: 900, share: "%2.57", bounceRate: 45, avgDuration: "5dk 30sn", avgDurationSec: 330, pagesPerVisit: 3.8, trend: "up", category: "içerik" },
      { path: "/kurumsal", traffic: 600, share: "%1.71", bounceRate: 62, avgDuration: "2dk 00sn", avgDurationSec: 120, pagesPerVisit: 2.0, trend: "stable", category: "kurumsal" },
    ],
  },
  {
    id: "mrb",
    name: "marbas.com.tr",
    domain: "marbas.com.tr",
    color: "#eab308",
    visits: 81137,
    visitsDisplay: "81.1K",
    globalRank: 570682,
    countryRank: 11633,
    authorityScore: 17,
    bounceRate: 59.93,
    pagesPerVisit: 1.61,
    avgDuration: "1dk 14sn",
    organicTraffic: "30.0K",
    organicChange: 5,
    paidTraffic: "0",
    paidChange: 0,
    refDomains: 100,
    refDomainsChange: 2,
    totalBacklinks: 516,
    backlinksChange: 3,
    aiTraffic: 10,
    channels: { direct: 55.85, organic: 40, referral: 1.91, social: 1.24, paid: 0, mail: 1 },
    keywords: [
      { rank: 1, keyword: "phe fon", position: 1, volume: 16030, trafficShare: "%19.76" },
      { rank: 2, keyword: "ekdmr", position: 1, volume: 9050, trafficShare: "%11.15" },
      { rank: 3, keyword: "pbr fon", position: 1, volume: 5270, trafficShare: "%6.50" },
      { rank: 4, keyword: "marbaş", position: 1, volume: 1450, trafficShare: "%4.20" },
      { rank: 5, keyword: "marbaş menkul", position: 1, volume: 490, trafficShare: "%2.80" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 60 }, { month: "Şub", value: 65 }, { month: "Mar", value: 51 },
      { month: "Nis", value: 110 }, { month: "May", value: 81 }, { month: "Haz", value: 81 },
    ],
    topPages: [
      { path: "/", traffic: 16030, share: "%19.76" },
      { path: "/fon", traffic: 9049, share: "%11.15" },
      { path: "/ekdmr", traffic: 5270, share: "%6.50" },
    ],
    pageDetails: [
      { path: "/", traffic: 16030, share: "%19.76", bounceRate: 58, avgDuration: "1dk 20sn", avgDurationSec: 80, pagesPerVisit: 1.6, trend: "down", category: "ana sayfa" },
      { path: "/fon", traffic: 9049, share: "%11.15", bounceRate: 52, avgDuration: "2dk 15sn", avgDurationSec: 135, pagesPerVisit: 2.0, trend: "stable", category: "fon" },
      { path: "/ekdmr", traffic: 5270, share: "%6.50", bounceRate: 48, avgDuration: "2dk 45sn", avgDurationSec: 165, pagesPerVisit: 2.3, trend: "up", category: "hisse" },
      { path: "/hisse", traffic: 1500, share: "%1.85", bounceRate: 55, avgDuration: "3dk 00sn", avgDurationSec: 180, pagesPerVisit: 2.5, trend: "stable", category: "hisse" },
      { path: "/kurumsal", traffic: 1000, share: "%1.23", bounceRate: 60, avgDuration: "1dk 45sn", avgDurationSec: 105, pagesPerVisit: 1.8, trend: "stable", category: "kurumsal" },
    ],
  },
  {
    id: "pus",
    name: "pusulayatirim.com.tr",
    domain: "pusulayatirim.com.tr",
    color: "#6366f1",
    visits: 8000,
    visitsDisplay: "8.0K",
    globalRank: 1000000,
    countryRank: 30000,
    authorityScore: 10,
    bounceRate: 75,
    pagesPerVisit: 1.50,
    avgDuration: "1dk 00sn",
    organicTraffic: "3.0K",
    organicChange: 0,
    paidTraffic: "0",
    paidChange: 0,
    refDomains: 30,
    refDomainsChange: 0,
    totalBacklinks: 200,
    backlinksChange: 0,
    aiTraffic: 5,
    channels: { direct: 60, organic: 30, referral: 5, social: 3, paid: 0, mail: 2 },
    keywords: [
      { rank: 1, keyword: "pusula yatırım", position: 1, volume: 500, trafficShare: "%8.50" },
      { rank: 2, keyword: "pusula menkul", position: 1, volume: 300, trafficShare: "%5.20" },
      { rank: 3, keyword: "canlı borsa", position: 15, volume: 368000, trafficShare: "%2.80" },
      { rank: 4, keyword: "borsa", position: 20, volume: 135000, trafficShare: "%1.50" },
      { rank: 5, keyword: "hisse", position: 18, volume: 35000, trafficShare: "%1.20" },
    ],
    monthlyVisits: [
      { month: "Oca", value: 7 }, { month: "Şub", value: 7 }, { month: "Mar", value: 8 },
      { month: "Nis", value: 8 }, { month: "May", value: 8 }, { month: "Haz", value: 8 },
    ],
    topPages: [
      { path: "/", traffic: 680, share: "%8.50" },
      { path: "/borsa", traffic: 224, share: "%2.80" },
      { path: "/iletisim", traffic: 120, share: "%1.50" },
    ],
    pageDetails: [
      { path: "/", traffic: 680, share: "%8.50", bounceRate: 75, avgDuration: "45sn", avgDurationSec: 45, pagesPerVisit: 1.3, trend: "stable", category: "ana sayfa" },
      { path: "/borsa", traffic: 224, share: "%2.80", bounceRate: 72, avgDuration: "1dk 00sn", avgDurationSec: 60, pagesPerVisit: 1.5, trend: "stable", category: "veri" },
      { path: "/iletisim", traffic: 120, share: "%1.50", bounceRate: 70, avgDuration: "30sn", avgDurationSec: 30, pagesPerVisit: 1.2, trend: "stable", category: "kurumsal" },
      { path: "/kurumsal", traffic: 80, share: "%1.00", bounceRate: 68, avgDuration: "1dk 30sn", avgDurationSec: 90, pagesPerVisit: 1.8, trend: "stable", category: "kurumsal" },
      { path: "/hisse", traffic: 60, share: "%0.75", bounceRate: 65, avgDuration: "2dk 00sn", avgDurationSec: 120, pagesPerVisit: 2.0, trend: "stable", category: "hisse" },
    ],
  },
];

export interface NavItem {
  href: string;
  label: string;
  icon: string;
  description: string;
}

export const NAV_ITEMS: NavItem[] = [
  { href: "/", label: "Genel Bakış", icon: "LayoutDashboard", description: "Temel metrikler ve özet" },
  { href: "/compare", label: "Domain Karşılaştırma", icon: "GitCompare", description: "Rakip analizi ve karşılaştırma" },
  { href: "/keywords", label: "Anahtar Kelimeler", icon: "Search", description: "Sıralama ve kelime performansı" },
  { href: "/traffic", label: "Trafik Analizi", icon: "BarChart3", description: "Kanal ve kaynak analizi" },
  { href: "/backlinks", label: "Backlink Analizi", icon: "Link2", description: "Backlink ve otorite analizi" },
];
